// src/App.tsx
// SPDX-License-Identifier: MIT OR LicenseRef-Moria-Angband
import { lazy, Suspense, useEffect, useState } from "react";
import styles from "./App.module.css";
import { draculaTheme } from "./dracula";
import { Menu, type Variant } from "./Menu";
import { applyPwaUpdate, pwaApplyingUpdate, usePwaUpdateAvailable } from "./pwa";
import { StartScreen } from "./StartScreen";
import { UpdateDialog } from "./UpdateDialog";
import type { HengbandActions } from "./useHengband";

const Hengband = lazy(() => import("./Hengband").then(({ Hengband }) => ({ default: Hengband })));

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  readonly userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}
interface Settings {
  fontSize: number;
  soundEnabled: boolean;
  musicEnabled: boolean;
  musicVolume: number;
  effectsVolume: number;
}

function parseFragment(hash: string): Variant | null {
  if (hash === "#ja") return "ja";
  if (hash === "#en") return "en";
  return null;
}

function loadSettings(): Settings {
  return {
    fontSize: Number(localStorage.getItem("hengband.fontSize")) || 14,
    soundEnabled: localStorage.getItem("hengband.sound") !== "false",
    musicEnabled: localStorage.getItem("hengband.music") !== "false",
    musicVolume: Number(localStorage.getItem("hengband.musicVolume") ?? "5"),
    effectsVolume: Number(localStorage.getItem("hengband.effectsVolume") ?? "5"),
  };
}

function useHashVariant(): Variant | null {
  const [variant, setVariant] = useState<Variant | null>(() => parseFragment(location.hash));
  useEffect(() => {
    function navigate(): void {
      const next = parseFragment(location.hash);
      if (variant === null) {
        if (next !== null) setVariant(next);
      } else location.reload();
    }
    window.addEventListener("hashchange", navigate);
    window.addEventListener("popstate", navigate);
    return () => {
      window.removeEventListener("hashchange", navigate);
      window.removeEventListener("popstate", navigate);
    };
  }, [variant]);
  return variant;
}

function useManifest(variant: Variant | null): void {
  useEffect(() => {
    if (variant === null) return;
    const link = document.createElement("link");
    link.rel = "manifest";
    link.href = `/${variant}.webmanifest`;
    link.type = "application/manifest+json";
    document.head.append(link);
    return () => link.remove();
  }, [variant]);
}

export function App() {
  const variant = useHashVariant();
  const [settings, setSettings] = useState(loadSettings);
  const [installPrompt, setInstallPrompt] = useState<BeforeInstallPromptEvent | null>(null);
  const [openOnlineHelp, setOpenOnlineHelp] = useState<(() => void) | null>(null);
  const [updateDialogOpen, setUpdateDialogOpen] = useState(false);
  const updateAvailable = usePwaUpdateAvailable();
  useManifest(variant);

  useEffect(() => {
    document.documentElement.style.setProperty("--fg-color", draculaTheme.foreground ?? null);
    document.documentElement.style.setProperty("--bg-color", draculaTheme.background ?? null);
    document.documentElement.style.setProperty("--bright-black", draculaTheme.brightBlack ?? null);
  }, []);
  useEffect(() => {
    document.documentElement.style.fontSize = `${settings.fontSize}px`;
  }, [settings.fontSize]);
  useEffect(() => {
    const beforeInstall = (event: Event) => {
      event.preventDefault();
      setInstallPrompt(event as BeforeInstallPromptEvent);
    };
    const installed = () => setInstallPrompt(null);
    window.addEventListener("beforeinstallprompt", beforeInstall);
    window.addEventListener("appinstalled", installed);
    return () => {
      window.removeEventListener("beforeinstallprompt", beforeInstall);
      window.removeEventListener("appinstalled", installed);
    };
  }, []);

  function save<K extends keyof Settings>(key: K, value: Settings[K], storageKey: string): void {
    setSettings((current) => ({ ...current, [key]: value }));
    localStorage.setItem(storageKey, String(value));
  }
  async function install(): Promise<void> {
    if (!installPrompt) return;
    await installPrompt.prompt();
    if ((await installPrompt.userChoice).outcome === "accepted") setInstallPrompt(null);
  }
  function ready(actions: HengbandActions): void {
    setOpenOnlineHelp(() => () => void actions.openOnlineHelp());
  }

  return (
    <div className={styles.app}>
      {variant === null ? (
        <StartScreen />
      ) : (
        <>
          <Menu
            variant={variant}
            {...settings}
            onFontSizeChange={(value) =>
              save("fontSize", Math.max(8, Math.min(32, value)), "hengband.fontSize")
            }
            onSoundEnabledChange={(value) => save("soundEnabled", value, "hengband.sound")}
            onMusicEnabledChange={(value) => save("musicEnabled", value, "hengband.music")}
            onMusicVolumeChange={(value) => save("musicVolume", value, "hengband.musicVolume")}
            onEffectsVolumeChange={(value) =>
              save("effectsVolume", value, "hengband.effectsVolume")
            }
            onInstall={installPrompt ? () => void install() : undefined}
            onUpdate={updateAvailable ? () => setUpdateDialogOpen(true) : undefined}
            onOnlineHelp={openOnlineHelp ?? undefined}
          />
          <UpdateDialog
            variant={variant}
            open={updateDialogOpen}
            onOpenChange={setUpdateDialogOpen}
            onConfirm={() => void applyPwaUpdate()}
          />
          <Suspense fallback={null}>
            <Hengband
              variant={variant}
              {...settings}
              isApplyingUpdate={pwaApplyingUpdate}
              onReady={ready}
              onExited={() => setOpenOnlineHelp(null)}
            />
          </Suspense>
        </>
      )}
    </div>
  );
}

// src/App.svelte
<script lang="ts">
import { onDestroy, onMount } from "svelte";
import { draculaTheme } from "./dracula";
import Menu from "./Menu.svelte";
import StartScreen from "./StartScreen.svelte";

interface BeforeInstallPromptEvent extends Event {
  prompt(): Promise<void>;
  readonly userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}

const hengbandModule = import("./Hengband.svelte");

document.documentElement.style.setProperty("--fg-color", draculaTheme.foreground ?? null);
document.documentElement.style.setProperty("--bg-color", draculaTheme.background ?? null);
document.documentElement.style.setProperty("--bright-black", draculaTheme.brightBlack ?? null);

type Variant = "ja" | "en";

function parseFragment(hash: string): Variant | null {
  if (hash === "#ja") return "ja";
  if (hash === "#en") return "en";
  return null;
}

let variant = $state<Variant | null>(parseFragment(location.hash));
let fontSize = $state(Number(localStorage.getItem("hengband.fontSize")) || 14);
let soundEnabled = $state(localStorage.getItem("hengband.sound") !== "false");
let musicEnabled = $state(localStorage.getItem("hengband.music") !== "false");
let deferredInstallPrompt = $state<BeforeInstallPromptEvent | null>(null);
let openOnlineHelp = $state<(() => void) | null>(null);

function handleFontSizeChange(size: number): void {
  const clamped = Math.max(8, Math.min(32, size));
  fontSize = clamped;
  localStorage.setItem("hengband.fontSize", String(clamped));
}

function handleSoundEnabledChange(enabled: boolean): void {
  soundEnabled = enabled;
  localStorage.setItem("hengband.sound", String(enabled));
}

function handleMusicEnabledChange(enabled: boolean): void {
  musicEnabled = enabled;
  localStorage.setItem("hengband.music", String(enabled));
}

function handleNavigation(): void {
  const next = parseFragment(location.hash);
  if (variant === null) {
    if (next !== null) variant = next;
  } else {
    location.reload();
  }
}

function handleBeforeInstallPrompt(e: Event): void {
  e.preventDefault();
  deferredInstallPrompt = e as BeforeInstallPromptEvent;
}

function handleAppInstalled(): void {
  deferredInstallPrompt = null;
}

async function handleInstall(): Promise<void> {
  if (!deferredInstallPrompt) return;
  await deferredInstallPrompt.prompt();
  const { outcome } = await deferredInstallPrompt.userChoice;
  if (outcome === "accepted") {
    deferredInstallPrompt = null;
  }
}

$effect(() => {
  document.documentElement.style.fontSize = `${fontSize}px`;
});

onMount(() => {
  window.addEventListener("hashchange", handleNavigation);
  window.addEventListener("popstate", handleNavigation);
  window.addEventListener("beforeinstallprompt", handleBeforeInstallPrompt);
  window.addEventListener("appinstalled", handleAppInstalled);
});

onDestroy(() => {
  window.removeEventListener("hashchange", handleNavigation);
  window.removeEventListener("popstate", handleNavigation);
  window.removeEventListener("beforeinstallprompt", handleBeforeInstallPrompt);
  window.removeEventListener("appinstalled", handleAppInstalled);
});
</script>

<svelte:head>
  {#if variant !== null}
    <link rel="manifest" href="/{variant}.webmanifest" type="application/manifest+json" />
  {/if}
</svelte:head>

<div class="app">
  {#if variant === null}
    <StartScreen />
  {:else}
    <Menu {variant} {fontSize} {soundEnabled} {musicEnabled} onFontSizeChange={handleFontSizeChange} onSoundEnabledChange={handleSoundEnabledChange} onMusicEnabledChange={handleMusicEnabledChange} onInstall={deferredInstallPrompt ? handleInstall : undefined} onOnlineHelp={openOnlineHelp ?? undefined} />
    {#await hengbandModule then { default: Hengband}}
      <Hengband {variant} {fontSize} {soundEnabled} {musicEnabled} onReady={({ openOnlineHelp: fn }) => { openOnlineHelp = fn; }} onExited={() => { openOnlineHelp = null; }} />
    {/await}
  {/if}
</div>

<style>
  :global(*) {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  :global(body) {
    font-family: monospace;
    height: 100vh;
    overflow: hidden;
    color: var(--fg-color);
    background-color: var(--bg-color);
  }

  .app {
    width: 100vw;
    height: 100vh;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }
</style>
