// src/Menu.svelte
<!-- SPDX-License-Identifier: MIT OR LicenseRef-Moria-Angband -->
<script lang="ts">
import { Menubar } from "bits-ui";
import StepperMenubarItem from "./StepperMenubarItem.svelte";

const {
  variant,
  fontSize,
  soundEnabled,
  musicEnabled,
  onFontSizeChange,
  onSoundEnabledChange,
  onMusicEnabledChange,
  musicVolume,
  effectsVolume,
  onMusicVolumeChange,
  onEffectsVolumeChange,
  onInstall,
  onOnlineHelp,
}: {
  variant: "ja" | "en";
  fontSize: number;
  soundEnabled: boolean;
  musicEnabled: boolean;
  onFontSizeChange: (size: number) => void;
  onSoundEnabledChange: (enabled: boolean) => void;
  onMusicEnabledChange: (enabled: boolean) => void;
  musicVolume: number;
  effectsVolume: number;
  onMusicVolumeChange: (volume: number) => void;
  onEffectsVolumeChange: (volume: number) => void;
  onInstall?: () => void;
  onOnlineHelp?: () => void;
} = $props();

async function handleFeedbackClick(e: MouseEvent) {
  e.preventDefault();
  const anchor = e.currentTarget as HTMLAnchorElement;

  const lines = [];
  lines.push(
    `- revision: ${import.meta.env.VITE_GIT_REVISION} (${import.meta.env.VITE_GIT_DESCRIPTION})`,
  );
  const wasmBuildId =
    variant === "ja"
      ? import.meta.env.VITE_WASM_BUILD_ID_JA
      : import.meta.env.VITE_WASM_BUILD_ID_EN;
  lines.push(`- variant: ${variant} (\`${wasmBuildId}\`)`);

  let highEntropySucceeded = false;
  if (navigator.userAgentData) {
    try {
      const ua = await navigator.userAgentData.getHighEntropyValues([
        "architecture",
        "fullVersionList",
        "model",
        "platform",
        "platformVersion",
      ]);
      const brands = (ua.fullVersionList ?? [])
        .filter((b) => b.brand !== "Not)A;Brand")
        .map((b) => `${b.brand}/${b.version}`)
        .join(", ");
      if (brands) lines.push(`- browser: ${brands}`);
      const platformInfo = [ua.platform, ua.platformVersion, ua.architecture]
        .filter(Boolean)
        .join(" ");
      if (platformInfo) lines.push(`- platform: ${platformInfo}`);
      if (ua.model) lines.push(`- model: ${ua.model}`);
      highEntropySucceeded = true;
    } catch {
      // fall through to userAgent fallback
    }
  }
  if (!highEntropySucceeded) {
    lines.push(`- userAgent: ${navigator.userAgent}`);
  }

  lines.push(`- client size: ${window.innerWidth}x${window.innerHeight}`);
  lines.push(`- pixel density: ${window.devicePixelRatio}`);
  lines.push(`- font size: ${fontSize}`);
  lines.push(`- standalone: ${window.matchMedia("(display-mode: standalone)").matches}`);

  try {
    const { usage, quota, usageDetails } = await navigator.storage.estimate();
    const quotaStr = quota != null ? ` / ${quota}` : "";
    if (usageDetails) {
      const details = Object.entries(usageDetails)
        .map(([k, v]) => `${k}: ${v}`)
        .join(", ");
      lines.push(`- storage: ${details}${quotaStr}`);
    } else if (usage != null) {
      lines.push(`- storage: ${usage}${quotaStr}`);
    }
  } catch {
    // storage estimate unavailable
  }

  const body = lines.join("\n");
  anchor.href = `https://github.com/hanazuki/hengband-web/issues/new?title=Feedback:%20&body=${encodeURIComponent(body)}`;
  window.open(anchor.href, "_blank");
}
</script>

<nav id="menu"
  ><Menubar.Root
    >{variant === "ja" ? "変愚蛮怒" : "Hengband"}<Menubar.Menu
      ><Menubar.Trigger
        >{variant === "ja" ? "ゲーム" : "Game"
      }</Menubar.Trigger
      >{#if onInstall}<Menubar.Portal
          ><Menubar.Content class="submenu"
            ><Menubar.Item onclick={onInstall}
              >{variant === "ja" ? "アプリをインストール…" : "Install app…"
            }</Menubar.Item
          ></Menubar.Content
        ></Menubar.Portal
      >{/if}</Menubar.Menu
    ><Menubar.Menu
      ><Menubar.Trigger
        >{variant === "ja" ? "表示" : "View"
      }</Menubar.Trigger
      ><Menubar.Portal
        ><Menubar.Content class="submenu"
          ><StepperMenubarItem value={fontSize} min={8} max={32} onChange={onFontSizeChange}
            >{variant === "ja" ? "文字サイズ" : "Font size"
          }</StepperMenubarItem
        ></Menubar.Content
      ></Menubar.Portal
    ></Menubar.Menu
    ><Menubar.Menu
      ><Menubar.Trigger
        >{variant === "ja" ? "音声" : "Audio"
      }</Menubar.Trigger
      ><Menubar.Portal
        ><Menubar.Content class="submenu"
          ><Menubar.CheckboxItem checked={musicEnabled} onCheckedChange={onMusicEnabledChange}
            >{variant === "ja" ? "楽曲" : "Music"}
          </Menubar.CheckboxItem
          ><Menubar.CheckboxItem checked={soundEnabled} onCheckedChange={onSoundEnabledChange}
            >{variant === "ja" ? "効果音" : "Effects"}
          </Menubar.CheckboxItem
          ><Menubar.Separator
          /><Menubar.Group
            ><Menubar.GroupHeading
              >{variant === "ja" ? "音量" : "Volume"
            }</Menubar.GroupHeading
            ><StepperMenubarItem value={musicVolume} min={0} max={10} onChange={onMusicVolumeChange}
              >{variant === "ja" ? "楽曲" : "Music"
            }</StepperMenubarItem
            ><StepperMenubarItem value={effectsVolume} min={0} max={10} onChange={onEffectsVolumeChange}
              >{variant === "ja" ? "効果音" : "Effects"
            }</StepperMenubarItem
          ></Menubar.Group
        ></Menubar.Content
      ></Menubar.Portal
    ></Menubar.Menu
    ><Menubar.Menu
      ><Menubar.Trigger
      >{variant === "ja" ? "ヘルプ" : "Help"}</Menubar.Trigger
      ><Menubar.Portal
        ><Menubar.Content class="submenu"
          ><Menubar.Item disabled={!onOnlineHelp} onclick={onOnlineHelp}
            >{variant === "ja" ? "オンライン・ヘルプ" : "Online help"
          }</Menubar.Item
          ><Menubar.Separator
          /><Menubar.Item
            ><a href="https://github.com/hanazuki/hengband-web/issues/new" onclick={handleFeedbackClick} target="_blank"
              >{variant === "ja" ? "フィードバックを送信" : "Send feedback"
            }</a
          ></Menubar.Item
          ><Menubar.Item
            ><a href="https://github.com/hanazuki/hengband-web" target="_blank"
              >{variant === "ja" ? "ソースコード" : "Go to source code"
            }</a
          ></Menubar.Item
          ><Menubar.Item
            ><a href="/licenses.txt" target="_blank"
              >{variant === "ja" ? "ライセンス表示" : "Software licenses"
            }</a
          ></Menubar.Item
        ></Menubar.Content
      ></Menubar.Portal
    ></Menubar.Menu
  ></Menubar.Root
></nav>

<style>
  #menu {
    font-family: monospace;
    font-size: 1rem;
    border-bottom: 1px solid currentcolor;
    user-select: none;

    & :global([data-menubar-root]) {
      display: flex;
      flex-direction: row;
      gap: 1ch;
    }

    & :global([data-menubar-root]) > :global([data-menubar-trigger]) {
      &::before { content: "[ "; }
      &::after { content: " ]"; }

      appearance: none;
      border: none;
      background: none;
      color: inherit;
      font: inherit;
      cursor: pointer;
    }
  }

  :global([data-menubar-content]) {
    padding: 0.5lh 0.5ch;
    background: var(--bg-color);
    font-size: 1rem;

    z-index: 10;

    border-width: 1lh 1ch;
    border-style: solid;
    border-image-source: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30"><text x="0" y="10" font-family="monospace" font-size="1rem" fill="white">┌─┐</text><text x="0" y="20" font-family="monospace" font-size="1rem" fill="white">│ │</text><text x="0" y="30" font-family="monospace" font-size="1rem" fill="white">└─┘</text></svg>');
    border-image-slice: 10;
    border-image-repeat: repeat;

    & a[href] {
      text-decoration: none;
      color: inherit;
      cursor: pointer;
    }
  }

  :global([data-menubar-separator]) {
    height: 1lh;
  }

  :global([data-menubar-group-heading]) {
    color: var(--bright-black);
  }

  :global([data-menubar-checkbox-item]) {
    cursor: pointer;

    &::before {
      content: "[ ] ";
    }

    &[data-state="checked"]::before {
      content: "[x] ";
    }
  }

  :global([data-menubar-item][data-disabled]) {
    color: var(--bright-black);
    cursor: default;
  }

  :global([data-menubar-sub-trigger]) {
    &::after {
      flex-grow: 1;
      content: " >";
      text-align: right;
    }
    display: flex;
    flex-direction: row;
  }
</style>

// src/Menu.tsx
// SPDX-License-Identifier: MIT OR LicenseRef-Moria-Angband
import { Menu as BaseMenu } from "@base-ui/react/menu";
import { Menubar } from "@base-ui/react/menubar";
import type { MouseEvent, ReactNode } from "react";
import styles from "./Menu.module.css";
import { Stepper } from "./Stepper";

export type Variant = "ja" | "en";

export interface MenuProps {
  variant: Variant;
  fontSize: number;
  soundEnabled: boolean;
  musicEnabled: boolean;
  onFontSizeChange(size: number): void;
  onSoundEnabledChange(enabled: boolean): void;
  onMusicEnabledChange(enabled: boolean): void;
  musicVolume: number;
  effectsVolume: number;
  onMusicVolumeChange(volume: number): void;
  onEffectsVolumeChange(volume: number): void;
  onInstall?(): void;
  onUpdate?(): void;
  onOnlineHelp?(): void;
}

interface StepperItemProps {
  children: ReactNode;
  value: number;
  min: number;
  max: number;
  onChange(value: number): void;
}

function StepperItem({ children, value, min, max, onChange }: StepperItemProps) {
  return (
    <BaseMenu.Item className={styles.stepperItem}>
      <span>{children}:</span>
      <Stepper value={value} min={min} max={max} onChange={onChange} />
    </BaseMenu.Item>
  );
}

interface MenuContentProps {
  children: ReactNode;
}

function MenuContent({ children }: MenuContentProps) {
  return (
    <BaseMenu.Portal>
      <BaseMenu.Positioner className={styles.positioner} align="start">
        <BaseMenu.Popup className={styles.popup}>{children}</BaseMenu.Popup>
      </BaseMenu.Positioner>
    </BaseMenu.Portal>
  );
}

export function Menu({
  variant,
  fontSize,
  soundEnabled,
  musicEnabled,
  onFontSizeChange,
  onSoundEnabledChange,
  onMusicEnabledChange,
  musicVolume,
  effectsVolume,
  onMusicVolumeChange,
  onEffectsVolumeChange,
  onInstall,
  onUpdate,
  onOnlineHelp,
}: MenuProps) {
  async function handleFeedbackClick(event: MouseEvent<HTMLAnchorElement>) {
    event.preventDefault();
    const lines = [
      `- revision: ${import.meta.env.VITE_GIT_REVISION} (${import.meta.env.VITE_GIT_DESCRIPTION})`,
      `- variant: ${variant}`,
    ];

    let highEntropySucceeded = false;
    if (navigator.userAgentData) {
      try {
        const ua = await navigator.userAgentData.getHighEntropyValues([
          "architecture",
          "fullVersionList",
          "model",
          "platform",
          "platformVersion",
        ]);
        const brands = (ua.fullVersionList ?? [])
          .filter((brand) => brand.brand !== "Not)A;Brand")
          .map((brand) => `${brand.brand}/${brand.version}`)
          .join(", ");
        if (brands) lines.push(`- browser: ${brands}`);
        const platformInfo = [ua.platform, ua.platformVersion, ua.architecture]
          .filter(Boolean)
          .join(" ");
        if (platformInfo) lines.push(`- platform: ${platformInfo}`);
        if (ua.model) lines.push(`- model: ${ua.model}`);
        highEntropySucceeded = true;
      } catch {
        // Fall through to the userAgent fallback.
      }
    }
    if (!highEntropySucceeded) lines.push(`- userAgent: ${navigator.userAgent}`);

    lines.push(`- client size: ${window.innerWidth}x${window.innerHeight}`);
    lines.push(`- pixel density: ${window.devicePixelRatio}`);
    lines.push(`- font size: ${fontSize}`);
    lines.push(`- standalone: ${window.matchMedia("(display-mode: standalone)").matches}`);

    try {
      const { usage, quota, usageDetails } = await navigator.storage.estimate();
      const quotaText = quota != null ? ` / ${quota}` : "";
      if (usageDetails) {
        const details = Object.entries(usageDetails)
          .map(([key, value]) => `${key}: ${value}`)
          .join(", ");
        lines.push(`- storage: ${details}${quotaText}`);
      } else if (usage != null) {
        lines.push(`- storage: ${usage}${quotaText}`);
      }
    } catch {
      // Storage estimates are not available in every browser.
    }

    const body = lines.join("\n");
    const href = `https://github.com/hanazuki/hengband-web/issues/new?title=Feedback:%20&body=${encodeURIComponent(body)}`;
    window.open(href, "_blank");
  }

  return (
    <nav className={styles.menu} id="menu">
      <Menubar className={styles.menubar}>
        <span>{variant === "ja" ? "変愚蛮怒" : "Hengband"}</span>

        <BaseMenu.Root>
          <BaseMenu.Trigger className={styles.trigger}>
            {onUpdate && <span className={styles.badge}>★</span>}
            {variant === "ja" ? "ゲーム" : "Game"}
          </BaseMenu.Trigger>
          {(onInstall || onUpdate) && (
            <MenuContent>
              {onInstall && (
                <BaseMenu.Item className={styles.item} onClick={onInstall}>
                  {variant === "ja" ? "アプリをインストール…" : "Install app…"}
                </BaseMenu.Item>
              )}
              {onInstall && onUpdate && <BaseMenu.Separator className={styles.separator} />}
              {onUpdate && (
                <BaseMenu.Item className={styles.item} onClick={onUpdate}>
                  <span className={styles.badge}>★</span>
                  {variant === "ja" ? "アップデートを適用…" : "Apply update…"}
                </BaseMenu.Item>
              )}
            </MenuContent>
          )}
        </BaseMenu.Root>

        <BaseMenu.Root>
          <BaseMenu.Trigger className={styles.trigger}>
            {variant === "ja" ? "表示" : "View"}
          </BaseMenu.Trigger>
          <MenuContent>
            <StepperItem value={fontSize} min={8} max={32} onChange={onFontSizeChange}>
              {variant === "ja" ? "文字サイズ" : "Font size"}
            </StepperItem>
          </MenuContent>
        </BaseMenu.Root>

        <BaseMenu.Root>
          <BaseMenu.Trigger className={styles.trigger}>
            {variant === "ja" ? "音声" : "Audio"}
          </BaseMenu.Trigger>
          <MenuContent>
            <BaseMenu.CheckboxItem
              checked={musicEnabled}
              className={styles.checkboxItem}
              onCheckedChange={onMusicEnabledChange}
            >
              {variant === "ja" ? "楽曲" : "Music"}
            </BaseMenu.CheckboxItem>
            <BaseMenu.CheckboxItem
              checked={soundEnabled}
              className={styles.checkboxItem}
              onCheckedChange={onSoundEnabledChange}
            >
              {variant === "ja" ? "効果音" : "Effects"}
            </BaseMenu.CheckboxItem>
            <BaseMenu.Separator className={styles.separator} />
            <BaseMenu.Group>
              <BaseMenu.GroupLabel className={styles.groupLabel}>
                {variant === "ja" ? "音量" : "Volume"}
              </BaseMenu.GroupLabel>
              <StepperItem value={musicVolume} min={0} max={10} onChange={onMusicVolumeChange}>
                {variant === "ja" ? "楽曲" : "Music"}
              </StepperItem>
              <StepperItem value={effectsVolume} min={0} max={10} onChange={onEffectsVolumeChange}>
                {variant === "ja" ? "効果音" : "Effects"}
              </StepperItem>
            </BaseMenu.Group>
          </MenuContent>
        </BaseMenu.Root>

        <BaseMenu.Root>
          <BaseMenu.Trigger className={styles.trigger}>
            {variant === "ja" ? "ヘルプ" : "Help"}
          </BaseMenu.Trigger>
          <MenuContent>
            <BaseMenu.Item className={styles.item} disabled={!onOnlineHelp} onClick={onOnlineHelp}>
              {variant === "ja" ? "オンライン・ヘルプ" : "Online help"}
            </BaseMenu.Item>
            <BaseMenu.Separator className={styles.separator} />
            <BaseMenu.LinkItem
              className={styles.linkItem}
              href="https://github.com/hanazuki/hengband-web/issues/new"
              onClick={handleFeedbackClick}
              rel="noopener"
              target="_blank"
            >
              {variant === "ja" ? "フィードバックを送信" : "Send feedback"}
            </BaseMenu.LinkItem>
            <BaseMenu.LinkItem
              className={styles.linkItem}
              href="https://github.com/hanazuki/hengband-web"
              rel="noopener"
              target="_blank"
            >
              {variant === "ja" ? "ソースコード" : "Go to source code"}
            </BaseMenu.LinkItem>
            <BaseMenu.LinkItem
              className={styles.linkItem}
              href="/licenses.txt"
              rel="noopener"
              target="_blank"
            >
              {variant === "ja" ? "ライセンス表示" : "Software licenses"}
            </BaseMenu.LinkItem>
          </MenuContent>
        </BaseMenu.Root>
      </Menubar>
    </nav>
  );
}
